# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-21 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_proj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('population', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('elevation', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Economy',
            fields=[
                ('state', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('gdp', models.FloatField(blank=True, null=True)),
                ('agriculture', models.FloatField(blank=True, null=True)),
                ('service', models.FloatField(blank=True, null=True)),
                ('industry', models.FloatField(blank=True, null=True)),
                ('inflation', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'economy',
            },
        ),
        migrations.CreateModel(
            name='Ethnicgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=50)),
                ('percentage', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ethnicgroup',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('personid', models.FloatField(blank=True, null=True)),
                ('number_of_emp', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'industry',
            },
        ),
        migrations.CreateModel(
            name='Ismember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=12)),
            ],
            options={
                'managed': False,
                'db_table': 'ismember',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField(blank=True, null=True)),
                ('occupatid', models.FloatField(blank=True, null=True)),
                ('personid', models.FloatField()),
                ('title', models.CharField(max_length=40)),
            ],
            options={
                'managed': False,
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=50)),
                ('percentage', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupatid', models.FloatField()),
                ('job_title', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'managed': False,
                'db_table': 'occupation',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=40)),
                ('state', models.CharField(blank=True, max_length=40, null=True)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('established', models.DateField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'organization',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('state', models.CharField(blank=True, max_length=40, null=True)),
                ('city', models.CharField(blank=True, max_length=25, null=True)),
                ('name', models.CharField(max_length=40)),
                ('dob', models.DateField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Population',
            fields=[
                ('state', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('state_population', models.FloatField(blank=True, null=True)),
                ('percent_pop_in_college', models.FloatField(blank=True, null=True)),
                ('emp_oversixteen', models.FloatField(blank=True, null=True)),
                ('emp_inlaborforce', models.FloatField(blank=True, null=True)),
                ('emp_notlaborforce', models.FloatField(blank=True, null=True)),
                ('emp_armedforces', models.FloatField(blank=True, null=True)),
                ('emp_unemployed', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'population',
            },
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=50)),
                ('percentage', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'religion',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('govid', models.FloatField()),
                ('budget', models.FloatField(blank=True, null=True)),
                ('numofemp', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('capital', models.CharField(max_length=40)),
                ('population', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'state',
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
